development:
  adapter: postgresql
  encoding: unicode
  database: truckspy_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: truckspy_development
  pool: 5
  host: localhost